baseURL = 'https://wisc-rt2.github.io/cs839_spring25/'
languageCode = 'en-us'
title = "CS839 Topics in Advanced Robotics"
theme = "hugo-book"
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true